// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNHJKSy9p9xukpOSIC7GWCLDf1mFPoGsU',
    appId: '1:1006304062807:web:cff829661458ffbceda212',
    messagingSenderId: '1006304062807',
    projectId: 'pfadi-uro',
    authDomain: 'pfadi-uro.firebaseapp.com',
    storageBucket: 'pfadi-uro.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGj9YDVjv0icP5EkEEFNlB1ukZAe-7x-Y',
    appId: '1:1006304062807:android:ef9aa005f5e42f89eda212',
    messagingSenderId: '1006304062807',
    projectId: 'pfadi-uro',
    storageBucket: 'pfadi-uro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj-BlG43Zv2ZN6ZbfqVO7w8vTJurJyKrc',
    appId: '1:1006304062807:ios:e1943dadf4b28707eda212',
    messagingSenderId: '1006304062807',
    projectId: 'pfadi-uro',
    storageBucket: 'pfadi-uro.appspot.com',
    iosBundleId: 'com.example.pfadiUro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj-BlG43Zv2ZN6ZbfqVO7w8vTJurJyKrc',
    appId: '1:1006304062807:ios:e1943dadf4b28707eda212',
    messagingSenderId: '1006304062807',
    projectId: 'pfadi-uro',
    storageBucket: 'pfadi-uro.appspot.com',
    iosBundleId: 'com.example.pfadiUro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNHJKSy9p9xukpOSIC7GWCLDf1mFPoGsU',
    appId: '1:1006304062807:web:8b8984b5321bd1b4eda212',
    messagingSenderId: '1006304062807',
    projectId: 'pfadi-uro',
    authDomain: 'pfadi-uro.firebaseapp.com',
    storageBucket: 'pfadi-uro.appspot.com',
  );
}
